[package]
name = "mdsplode"
description = "A CLI tool for exploding and serialising Markdown files (metadata, AST, rendered parts, and rendered whole)"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Duncan McGreggor <oubiwann@gmail.com>"]
repository = "https://github.com/oxur/mdsplode"
documentation = "https://docs.rs/mdsplode/"
exclude = ["/.github", "/resources", ".gitignore"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = { version = "1.0.0-alpha.16", features = ["serde"] }
serde = "1.0.193"
serde_json = "1.0.108"
toml = "0.8.8"
versions = "6.0.0"

[[bin]]
name = "mdsplode"
